# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('ui/style.qss', 'ui'),
        ('ui/light.qss', 'ui'),
        ('ui/assets/alas.ico', 'ui/assets'),
        ('ui/assets/bottom_icons/settings.png', 'ui/assets/bottom_icons'),
        ('ui/assets/bottom_icons/settings_hover.png', 'ui/assets/bottom_icons'),
        ('ui/assets/bottom_icons/home.png', 'ui/assets/bottom_icons'),
        ('ui/assets/bottom_icons/home_hover.png', 'ui/assets/bottom_icons'),
        ('ui/assets/bottom_icons/float.png', 'ui/assets/bottom_icons'),
        ('ui/assets/bottom_icons/float_hover.png', 'ui/assets/bottom_icons'),
        ('ui/assets/bottom_icons/log.png', 'ui/assets/bottom_icons'),
        ('ui/assets/bottom_icons/log_hover.png', 'ui/assets/bottom_icons'),
        ('ui/assets/bottom_icons/export.png', 'ui/assets/bottom_icons'),
        ('ui/assets/bottom_icons/export_hover.png', 'ui/assets/bottom_icons'),
        ('ui/assets/bottom_icons/upload.png', 'ui/assets/bottom_icons'),
        ('ui/assets/bottom_icons/upload_hover.png', 'ui/assets/bottom_icons'),
        ('ui/assets/bottom_icons/delete.png', 'ui/assets/bottom_icons'),
        ('ui/assets/bottom_icons/delete_hover.png', 'ui/assets/bottom_icons'),
        ('ui/assets/bottom_icons/delete_disabled.png', 'ui/assets/bottom_icons'),
        ('resources/fastapi_payload.txt', 'resources'),
    ],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'unittest',
        'pytest',
        'test',
        'matplotlib',
        'numpy',
        'PIL',
        'Pillow',
        'pkg_resources',
    ],
    noarchive=False,
    optimize=2,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='Alas-Gyre',
    debug=False,
    bootloader_ignore_signals=False,
    strip=True,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='ui/assets/alas.ico'
)
